version: "3.9"
services:
  fastapi:
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      - uvicorn
      - main:app
      - --host
      - 0.0.0.0
      - --reload
